version: '3'

services:
  act-login-88:
    image: w88700126/act-login:latest
    restart: always
    privileged: true
    ports:
      - 14411:14411
    volumes:
      - ./log/log88:/server/log/
    command: "/usr/bin/supervisord -c /etc/supervisord.conf -n"

  act-pvp-90:
    image: w88700126/act-pvp:latest
    restart: always
    privileged: true
    ports:
      - 14520:14520
      - 14521:14521
    volumes:
      - ./log/log90:/server/log/
    command: "/usr/bin/supervisord -c /etc/supervisord.conf -n"

  act-game-1:
    image: w88700126/act-game:latest
    restart: always
    privileged: true
    ports:
      - 10062:10062
    environment:
      - ZONEID=1
    volumes:
      - ./log/log1:/server/log/
    command: "/usr/bin/supervisord -c /etc/supervisord.conf -n"